dramas = ['Little Womem','Big Mouth','Extraordinary Attorney Woo','Alchemy of Souls','Business Proposal','Hometown Cha-Cha-Cha','All of Us Are Dead','Squid Game','Penthouse','Crash Landing On You','Hotel Del Luna','A Korean Odyssey','Reply 1988','Boys Over Flowers','Dream High']
descriptions = ["Three sisters get involved in a case that leads them to fight against the richest and most influential family in South Korea. Oh In-Joo (Kim Go-Eun) is the oldest sister. She grew up in a terribly poor environment and she is still poor. Since she was a young child, she realized that money was the most important thing to protect herself and her family. Her dream is to live an ordinary life like other people. She gets involved in a case that could change her life. Oh In-Kyung (Nam Ji-Hyun) is the middle sister. She is an enthusiastic reporter at a news station. She believes in doing the right things. She also has always been poor, but money doesn't rule life. She now begins to dig into a mysterious case that she first faced when she first became a reporter. Oh In-Hye (Park Ji-Hu) is the youngest of the three sisters. She is a student at a prestigious arts high school and she has a natural talent for painting. She often feels her two older sisters’ love for her is too much.",
                "Park Chang-Ho (Lee Jong-Suk) works as a lawyer with a measly 10% winning rate. He is a talkative person and, because of this people call him Big Mouth. He happens to get involved in a murder case and he is somehow fingered as genius swindler Big Mouse. Due to this, Park Chang-Ho finds himself in a life-threatening situation. Meanwhile, Go Mi-Ho (Lim Yoon-A) is Park Chang-Ho’s wife and she works as a nurse. She has a beautiful appearance and a personality that is both wise and brave. She helped her husband become a lawyer by supporting him financially and psychologically. Go Mi-Ho learns that Park Chang-Ho is suspected to be the genius swindler Big Mouse and attempts to clear her husband's name.",
                "Woo Young-Woo (Park Eun-Bin) is extremely smart and she also has autism spectrum disorder. She never forgets what she sees, but she lacks in social skills and empathy. Woo Young-Woo begins to work as a trainee lawyer at a large law firm. While working there, she faces prejudice and irrationality against her, but she solves cases with her own unique perspective and grows as a lawyer.",
                "The fate of these people become twisted due to 'hwanhonsool' (the soul of the dead return to the living). In the country of Daeho, Jang Uk (Lee Jae-Wook) comes from the noble Jang family. He holds an unpleasant secret about his birth, which people all around the country talk about. He is troublemaker. Jang Ukk happens to meet Mu-Deok (Jung So-Min). She is an elite warrior, but her soul is trapped in a physically weak body. She becomes Jang Wook’s servant, but she also secretly teaches him how to fight. Seo Yul (Minhyun) comes from the noble Seo family. He seems perfect with good appearance, intelligence, and strong martial arts skills. Go Won (Shin Seung-Ho) is the crown prince of Daeho. He hopes to become a generous king.",
                "Shin Ha-Ri (Kim Se-Jeong) is a single woman and works for a company. She has a male friend and she has held a crush on him for a long time, but she learns that her friend has a girlfriend. Shin Ha-Ri feels sad and decides to meet her friend Jin Young-Seo, who is a daughter of a chaebol family. Jin Young-Seo then asks Shin Ha-Ri to take her place in a blind date and even offers some money for her time. Shin Ha-Ri accepts her friend's offer. She goes out on the blind date as Jin Young-Seo, while having the intention to get rejected by her date. When she sees her blind date, Shin Ha-Ri is dumbfounded. Her blind date is Kang Tae-Moo (Ahn Hyo-Seop). He is the CEO of the company where she works. Kang Tae-Moo is the CEO of a company that his grandfather founded. One day, his grandfather informed him of an upcoming blind date that he set up for him. Kang Tae-Moo is a workaholic and he is annoyed that his grandfather sets up blind dates for him. He decides to marry the next woman whom he meets at a blind date, so he won't be disturbed from his work anymore. That woman is Shin Ha-Ri, but pretending to be Jin Young-Seo. On the following day, Shin Ha-Ri receives a phone call from Kang Tae-Moo. He asks her to marry him.",
                "Yoon Hye-Jin (Shin Min-A) works as a dentist. She is mostly a realist, but due to her rightfulness, which is only a tiny part of her mind, her life changes. She ends up moving to the seaside village of Gongjin. There, Yoon Hye-Jin meets Hong Du-Sik (Kim Sun-Ho). She becomes curious about him. Hong Du-Sik is called Chief Hong by the local residents. He is a handsome and smart man. Officially, he is unemployed, but he always seems busy. If somebody needs help, Hong Du-Sik is the first one to appear and provide help.",
                "A virus outbreak occurs at Hyosan High School. The infected quickly turn into human eating zombies. Students at the high school must now fight for their lives, while they look for a way out. Nam On-Jo (Park Ji-Hu) & Lee Cheong-San (Yoon Chan-Young) have been friends since they were children. They are two of the students trapped in a classroom and surrounded by flesh eating zombies. Meanwhile, the Korean military work to isolate the outbreak and protect the country from an even larger outbreak.",
                "Seong Gi-Hun (Lee Jung-Jae) gets fired from his job. His life is miserable. Seong Gi-Hun hears about a secret survival game, with a 45.6 billion won prize for the winner. He decides to take part in the game. Meanwhile, Cho Sang-Woo (Park Hae-Soo) is like a brother to Seong Gi-Hun and vice versa. They grew up in the same neighborhood. Despite his poor family background, Cho Sang-Woo graduated from a prestigious university and found a good job. He now faces a crisis, due to misappropriation of company funds. He decides to take part in the secret survival game with Seong Gi-Hun.",
                "Shim Su-Ryeon (Lee Ji-Ah) was born into wealth. She is now an elegant woman of the upper class and she is like the queen of the Penthouse Apartment. Her husband is Joo Dan-Tae (Uhm Ki-Joon). He is successful in business and real estate. Cheon Seo-Jin (Kim So-Yeon) was born into a wealthy family. She is arrogant. Her husband is Ha Yoon-Cheol (Yoon Jong-Hoon). He is a chief surgeon at a general hospital and an ambitious man. Oh Yoon-Hee (Eugene) comes from a poor family background. She works hard for her children's success. She wants to belong to the upper class for her children.",
                "Yoon Se-Ri (Son Ye-Jin) is an heiress to a conglomerate in South Korea. One day, while paragliding, an accident caused by strong winds leads Yoon Se-Ri to make an emergency landing in North Korea. There, she meets Ri Jeong-Hyeok (Hyun-Bin), who is a North Korean army officer. He tries to protect her and hide her. Soon, Ri Jeong-Hyeok falls in love with Yoon Se-Ri.",
                "Jang Man-Wol (IU) is the CEO of Hotel del Luna. The hotel is situated in downtown in Seoul and has a very old appearance. She made a big error many years ago and, because of this, she has been stuck at Hotel del Luna. She is beautiful, but she is fickle, suspicious and greedy. Koo Chan-Sung (Yeo Jin-Goo) worked as the youngest assistant manager ever at a multinational hotel corporation. He is a sincere perfectionist. He looks level-headed, but he actually has a soft disposition. Due to an unexpected case, he begins to work as a manager at Hotel del Luna. The hotel's clientele consists of ghosts.",
                "In 2017, Son O-Gong and Woomawang (Cha Seung-Won) are in conflict with each other and they look for a true light in a dark world where evils exists everywhere.",
                "In 1988, Duk-Sun (Hyeri), Jung-Hwan (Ryoo Joon-Yeol), Sun-Woo (Ko Gyung-Pyo) and Dong-Ryong (Lee Dong-Hwi) are high school students and Taek (Park Bo-Gum) is a go player. These five people have been friends since they were little kids. They all grew up together and are neighbors to this day. Their families are also very close to each other. They always hang around Taek's room and spend time together.",
                "Set at a famous high school for the super-wealthy, this is a puppy love story centered on a poor girl and the F4 gang of rich kids headed by the rough and fearless Jun-pyo Koo. Geum Jan-Di (Hye-seon Ku) is a girl from a poor family but has an unrivaled sense of optimism and drive and is by chance admitted to a prestigious private high school. There she meets the infamous group of four astonishingly good looking and rich boys who are known as F4. The group's leader is Koo Jun-Pyo (Min-ho Lee), who is a spoiled heir to world-leading conglomerate Shinhwa. He is joined by mysterious and breathlessly handsome Yun Ji-Hu (Hyeon-jung Kim), So Lee-Jeong (Kim Beom), and Song Woo-Bin (Kim Jun). Their love story moves from Seoul to New Caledonia to Macau.",
                "'Dream High' takes place at Kirin High School of Art and follows the lives of students as they aspire to become superstars. Song Sam-Dong (Kim Soo-Hyun) lives in the country side and dreams of becoming an owner of a stock farm. He falls in love with Ko Hye-Mi (Bae Suji) at first sight and follows her to Kirin High School of Art. There he discovers his genius like musical talent. Jin-Gook (TaecYeon) is a gifted dancer, but a troubled student at school. The director of Kirin High School of Art (Bae Yong-Joon)) recommends to Jin-Gook to enroll at his school. There, Jin-Gook's talents blossom and he now dreams of becoming a global star. Exchange student Jason (Wooyoung) comes to Kirin High after receiving the top score for new applicants. He comes from abroad and shows outstanding skills as a dancer. Ko Hye-Mi (Bae Suzy) is the most popular girl at Kirin High. She carries herself as a confident girl, but inside hides a sad past. She dreamed of becoming a world renown classical vocalist, but after the collapse of her family she had no choice but to enter Kirin High School of Art. She is loved by Song Sam-Dong and Jin-Gook. Yoon Becky (Eun Jung) looks up to Ko Hye-Mi, who appears to have everything. They soon become rivals. Eria (Yoon Young-Ah) is a popular teen star. She enters Kirin High School of Art and becomes the object of admiration by her peers. She looks forward to having a 'regular' school life."]

print("This is Python k-drama service. This program will introduce you the plot details of each drama in Python k-drama.")
while True:
  print("\nPython k-drama")
  print("="*50)

  for i in range(len(dramas)):
    print(i+1,dramas[i])

  print("="*50)

  num = input("Choose the number of drama that you like to know about:")
  if num.isdigit() and  int(num)>=1 and int(num)<=15:
    num = int(num)
    print("\n"+dramas[num-1]+"\n"+descriptions[num-1])
  else:
    print("\nWrong input. The number should be between 1 and 15")
  
  ch = input("\nDo you like to quit? y/n:")
  if ch.lower() == 'y':
    str = "GoodBye"
    for i in range(len(str)):
        print(" "*(len(str)-i),"*"*i,str[i],"*"*i," "*(len(str)-i))
    break
